name: 'Deploy GitHub Pages'

on:
  push:
    tags: 'v*'
  workflow_dispatch:

permissions:
  contents: 'read'
  pages: 'write'
  id-token: 'write'

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: false

jobs:
  build:
    if: |-
      ${{ !contains(github.ref_name, 'nightly') }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # v6

      - name: 'Setup Python'
        uses: 'actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405' # v6
        with:
          python-version: '3.x'

      - name: 'Install MkDocs Material'
        run: pip install -r requirements.txt

      - name: 'Build with MkDocs'
        run: mkdocs build --strict

      - name: 'Upload artifact'
        uses: 'actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b' # v4
        with:
          path: site/

  deploy:
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    runs-on: 'ubuntu-latest'
    needs: 'build'
    steps:
      - name: 'Deploy to GitHub Pages'
        id: 'deployment'
        uses: 'actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e' # ratchet:actions/deploy-pages@v4
