name: Template
on:
  workflow_dispatch:
  #schedule: [{cron: "0 0 * * 0"}]
  #push:
    #branches: [main, master]
  #pull_request:
    #branches: [main, master]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
  checks: write
  packages: read
env:
  DEBIAN_FRONTEND: noninteractive
  LC_ALL: C
  GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

jobs:
  run:
    name: Template
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk space
        id: Debloat
        run: |
          df -h; sudo apt-get autoclean -y; sudo apt-get autoremove --purge -y
          command -v docker &>/dev/null && docker system prune -a -f
          sudo rm -f /var/lib/man-db/auto-update
          sudo rm -rf "/var/lib/apt/lists/"* /opt/ghc /usr/local/.ghcup /usr/local/lib/android /usr/share/dotnet
          echo "force-unsafe-io" | sudo tee -a /etc/dpkg/dpkg.cfg.d/force-unsafe-io
          INITRAMFS_CONF="/etc/initramfs-tools/update-initramfs.conf"; DPKG_TRIGGERS="/var/lib/dpkg/triggers/File"
          [[ -e /etc/initramfs-tools/update-initramfs.conf ]] && sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
          if [[ -e $DPKG_TRIGGERS ]]; then
            sudo sed '/fontconfig/d' -i $DPKG_TRIGGERS; sudo sed '/install-info/d' -i $DPKG_TRIGGERS
            sudo sed '/mime/d' -i $DPKG_TRIGGERS;  sudo sed '/hicolor-icon-theme/d' -i $DPKG_TRIGGERS
          fi
          echo -e "\nFree space:"; df -h
        continue-on-error: true
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      # Add your workflow steps here
